Update to newer alignment package format
panda-official/DriftProtocol pull request #4
Opened 2022-08-22 14:10 UTC by aschenbecherwespe

**Closes** #

### Please check if the PR fulfills these requirements

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md have been updated (for bug fixes / features / docs)

### What kind of change does this PR introduce?

(Bug fix, feature, docs update, ...)

### What is the current behavior?

(You can also link to an open issue here)

### What is the new behavior?

(if this is a feature change)

### Does this PR introduce a breaking change?** 

(What changes might users need to make in their application due to this PR?)

### Other information:

2022-08-22 14:48 UTC, atimin requested changes

2022-08-22 14:48 UTC, atimin commented on CHANGELOG.md
> +- HOTFIX: update to newer alignment package format, [PR-4](https://github.com/panda-official/DriftProtocol/pull/4)
Please add Removed section.

2022-08-23 05:56 UTC, aschenbecherwespe commented on CHANGELOG.md
> +- HOTFIX: update to newer alignment package format, [PR-4](https://github.com/panda-official/DriftProtocol/pull/4)
i think i've done that now!

2022-08-23 09:34 UTC, atimin approved these changes

2022-08-23 09:35 UTC, merged